module.exports = {
  FIELD_LIMITS: {
    USERNAME: 50,
    PASSWORD: 25,
    HOSPITAL_NAME: 150,
    PATIENT_NAME: 150,
    PATIENT_ID: 64,
    FROM_HOSPITAL: 150,
    TO_HOSPITAL: 150,
    DEPARTMENT: 100,
    REASON_FOR_TRANSFER: 500,
    DIAGNOSIS: 500,
    CLINICAL_SUMMARY_MAX_WORDS: 200,
    ALLERGY_ITEM: 150,
    DRUG_NAME: 150,
    DOSE: 100,
    ROUTE: 50,
    FREQUENCY: 100,
    MEDICATION_NOTES: 500,
    VITAL_NOTES: 500,
    INVESTIGATION_NAME: 150,
    INVESTIGATION_NOTES: 500,
    OTHER_DETAIL_TITLE: 100,
    OTHER_DETAIL_VALUE: 2000,
    ARRIVAL_NOTE: 1000,
    DISCREPANCY_NOTE: 1000,
    PROFILE_NAME: 150,
    OTP: 6
  },
  ARRAY_LIMITS: {
    ALLERGIES: 20,
    MEDICATIONS: 50,
    INVESTIGATIONS: 50,
    OTHER_DETAILS: 20
  },
  OTP_CONFIG: {
    EXPIRATION_MINUTES: 5,
    MAX_ATTEMPTS: 5,
    RESEND_COOLDOWN_SECONDS: 60,
    MAX_HOURLY_REQUESTS: 5
  },
  ENUMS: {
    OTHER_DETAIL_CATEGORIES: [
      "NURSING",
      "DIETARY",
      "MOBILITY",
      "PROCEDURE",
      "DEVICE",
      "FAMILY",
      "SOCIAL",
      "ADMINISTRATIVE",
      "FOLLOW_UP",
      "SPECIAL_INSTRUCTIONS",
      "OTHER"
    ],
    OTHER_DETAIL_PRIORITIES: ["NORMAL", "IMPORTANT", "CRITICAL"],
    TRANSFER_PRIORITIES: ["Routine", "Urgent", "Emergency"],
    TRANSFER_STATUSES: ["IN_TRANSIT", "RECEIVED", "DISCREPANCY", "UPDATED"],
    ARRIVAL_CONDITIONS: ["Stable", "Unstable"],
    ROLES: ["doctor", "patient"]
  }
};
